language: python

#
# Test test matrix is spelled out explicitly here.
#
# For each supported version of Python, we will test with coverage.
#
matrix:
  include:
  - python: 3.8
    env: TOXENV=pep8
  - python: 3.8
    env: TOXENV=py38-pylint
  - python: 3.8
    env: TOXENV=docs

  - python: 3.8
    env: TOXENV=py38-pytest
  - python: 3.7
    env: TOXENV=py37-pytest
  - python: 3.6
    env: TOXENV=py36-pytest

  # Failures on these unsupported python versions are allowed
  # allow_failures:
  # - env: TOXENV=


install:
- pip install -U setuptools wheel pip
- pip install tox
script:
- tox -vvv

notifications:
  email: false
